// Copyright (C) 2021  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 21.1 (Build Build 842 10/21/2021)
// Created on Sun May  8 19:39:48 2022

uart uart_inst
(
	.i_Clock(i_Clock_sig) ,	// input  i_Clock_sig
	.i_Rx_Serial(i_Rx_Serial_sig) ,	// input  i_Rx_Serial_sig
	.o_Tx_Active(o_Tx_Active_sig) ,	// output  o_Tx_Active_sig
	.o_Tx_Serial(o_Tx_Serial_sig) ,	// output  o_Tx_Serial_sig
	.o_Tx_Done(o_Tx_Done_sig) 	// output  o_Tx_Done_sig
);

defparam uart_inst.c_CLKS_PER_BIT = 5208;
